#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Django settings for i3jf project.

Generated by 'django-admin startproject' using Django 1.10.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'c_l8w+!50t$rm-$d!-mfuu088v9v!08ug)o4dgdua5n(69o$^^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']
#ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # 'xadmin',
    # 'crispy_forms',
    # 'reversion',

    'captcha',
    'mptt',
    'product',
    'authx',
    'recharge',
    'area',
    "main",
    "order",
    'oam',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    #'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware',
]

ROOT_URLCONF = 'i3jf.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # 'DIRS': [ os.path.join( os.getcwd(), 'html')],
        'DIRS': [ os.path.join( BASE_DIR, 'html')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'i3jf.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'srv_i3jf_db',
        'USER': 'postgres',
        'PASSWORD': '123456',
        'HOST': '127.0.0.1',
        'PORT': '5432',
    },
}


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

# LANGUAGE_CODE = 'en'
LANGUAGE_CODE = 'zh-hans'

# TIME_ZONE = 'UTC'
TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

MEDIA_ROOT = 'upload/'
MEDIA_URL = '/upload/'
STATIC_URL = '/static/'
CAPTCHA_URL = '/captcha/'
STATIC_ROOT = os.path.join(BASE_DIR,"static")

CAPTCHA_DIR = os.path.join( BASE_DIR, 'temp')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "html"),
    os.path.join(BASE_DIR, "temp"),
]
if not os.path.exists(STATICFILES_DIRS[1]):
    os.mkdir(STATICFILES_DIRS[1])


DEFAULT_SMS_VALIDATION_DEBUG_CODE_MAX = 10000
DEFAULT_SMS_VALIDATION_EXPIRE_IN_SEC = 30

if DEBUG == True:
    PAY_PARAM ={
    'cm_pay':{
    'sign_key': '0HgNAeOyG0B3DkDuzLUwC4AYW1GX1BtEOPIlKnMl0EVYMYXweQxMUiXs1hNnbptJ',
    'req_url' : "https://ipos.10086.cn/ips/cmpayService",
    'merchant_id' : '888073157340001' # 商户号
    },
    }
else:
    PAY_PARAM ={
    'cm_pay':{
    'sign_key': 'eOKkIpYrMutBK38NAWgMudLMbdrf7OCVwnJK1L64Exhhqq9uUevLkWiZfIf0WV15',
    'req_url' : "https://ipos.10086.cn/ips/cmpayService",
    'merchant_id' : '888009962120010' # 商户号
    },
    }

API_PARAM ={
    'key': 'eOKkIpYrMutBK38NAWgMudLMbdrf7OCVwnJK1L64Exhhqq9uUevLkWiZfIf0WV15',
    'secret' : "https://ipos.10086.cn/ips/cmpayService",
    'token' : "https://ipos.10086.cn/ips/cmpayService",
    'req_url' : 'https://127.0.0.1/i3jf/api' # 商户号
}
LOGIN_URL = '/api/user/login'


# URL = 'http://127.0.0.1:8000/i3jf/'
# URL = 'http://192.168.1.80:8000/i3jf/'
# URL = 'http://192.168.1.68:8000/i3jf/'
URL = "http://api.i3jf.com/i3jf/"  # 正式环境
# URL = "http://test.i3jf.com/i3jf/" # 测试环境

# ACCESSTOKEN = "28e7d374-729c-11e7-918c-704d7bb2a50b" # 自己账户
# ACCESSTOKEN = "6a1d2da1-7722-11e7-bd66-4ccc6a46b6ed" # 本地测试账号
# ACCESSTOKEN = "8cc547c2-77ed-11e7-a65e-00163e003f69" # 服务测试账号
ACCESSTOKEN = "25a9fcaa-818d-11e7-a78e-00163e0f0342" # i3jf账号
# APPKEY = "cxgj"
APPKEY = "i3jf"
# APPKEY = "ljs"
CHANNELSN = "sn"
# CHANNELSN = "i3jf"

# LOGGING = {
#     'version': 1,
#     'disable_existing_loggers': False,
#
#     'handlers': {
#         'file': {
#             'level': 'WARN',
#             'class': 'logging.FileHandler',
#             'filename': os.path.join( BASE_DIR, 'debug.log'),
#         },
#     },
#
#     'loggers': {
#         'django': {
#             'handlers': ['file'],
#             'level': 'DEBUG',
#             'propagate': True,
#         },
#     },
# }

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'standard': {
            'format': '[%(asctime)s][%(threadName)s:%(thread)d][task_id:%(name)s][%(filename)s:%(lineno)d]'
                      '[%(levelname)s][%(message)s]'
        },
        'simple': {
            'format': '[%(levelname)s][%(asctime)s][%(filename)s:%(lineno)d]%(message)s'
        },
        'collect': {
            'format': '%(message)s'
        }
    },
    'filters': {
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'filters': ['require_debug_true'],
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        },
        'default': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',  # 保存到文件，自动切
            'filename': os.path.join(BASE_DIR, "debug.log"),  # 日志文件
            'maxBytes': 1024 * 1024 * 50,  # 日志大小 10M
            'backupCount': 3,
            'formatter': 'standard',
            'encoding': 'utf-8',
        },
        'error': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',  # 保存到文件，自动切
            'filename': os.path.join(BASE_DIR, "debug.log"),  # 日志文件
            'maxBytes': 1024 * 1024 * 50,  # 日志大小 10M
            'backupCount': 5,
            'formatter': 'standard',
            'encoding': 'utf-8',
        },
        'collect': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',  # 保存到文件，自动切
            'filename': os.path.join(BASE_DIR, "debug.log"),
            'maxBytes': 1024 * 1024 * 50,  # 日志大小 10M
            'backupCount': 5,
            'formatter': 'collect',
            'encoding': "utf-8"
        }
    },
    'loggers': {
        '': {
            'handlers': ['default', 'console', 'error'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'collect': {
            'handlers': ['console', 'collect'],
            'level': 'INFO',
        }
    },
}

ALI_SMS_API={
    'SMS_RegisterTemplate':'SMS_81560036',
    'SMS_ForgetPasswordTemplate':'SMS_92555005',
    'SMS_ChangeTelephoneForOldTemplate':'SMS_92610003',
    'SMS_ChangeTelephoneForNewTemplate':'SMS_92685001',
    'SMS_PayPasswordTemplate':'SMS_92485008',
}