# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-05 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('level', models.CharField(max_length=20, null=True)),
                ('pId', models.CharField(max_length=20, null=True)),
                ('nid', models.CharField(max_length=20, null=True)),
            ],
            options={
                'verbose_name': '\u5e02/\u533a',
                'verbose_name_plural': '\u5e02/\u533a',
            },
        ),
        migrations.CreateModel(
            name='DistrictModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, null=True)),
                ('level', models.CharField(max_length=20, null=True)),
                ('pId', models.CharField(max_length=20, null=True)),
                ('nid', models.CharField(max_length=20, null=True)),
            ],
            options={
                'verbose_name': '\u53bf',
                'verbose_name_plural': '\u53bf',
            },
        ),
        migrations.CreateModel(
            name='ProvinceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('level', models.CharField(max_length=20, null=True)),
                ('pId', models.CharField(max_length=20, null=True)),
                ('nid', models.CharField(max_length=20, null=True)),
            ],
            options={
                'verbose_name': '\u7701',
                'verbose_name_plural': '\u7701',
            },
        ),
        migrations.CreateModel(
            name='TownModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('level', models.CharField(max_length=20, null=True)),
                ('pId', models.CharField(max_length=20, null=True)),
                ('nid', models.CharField(max_length=20, null=True)),
                ('secondPid', models.CharField(max_length=20, null=True)),
            ],
            options={
                'verbose_name': '\u4e61/\u9547',
                'verbose_name_plural': '\u4e61/\u9547',
            },
        ),
    ]
