# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-12 01:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0002_auto_20170912_0944'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='townmodel',
            unique_together=set([]),
        ),
    ]
