# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-12 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0003_auto_20170912_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='citymodel',
            name='snid',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='districtmodel',
            name='snid',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='provincemodel',
            name='snid',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='townmodel',
            name='snid',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
