# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-16 06:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authx', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RechargeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(default='', max_length=128, verbose_name='\u5546\u6237\u8ba2\u5355\u53f7')),
                ('payno', models.CharField(default='', max_length=128, verbose_name='\u6d41\u6c34\u53f7')),
                ('state', models.IntegerField(choices=[(0, 'Normal'), (1, 'Abnormal')], default=0, verbose_name='\u72b6\u6001')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='\u652f\u4ed8\u91d1\u989d')),
                ('return_code', models.CharField(default='', max_length=10, verbose_name='\u8fd4\u56de\u7801')),
                ('message', models.CharField(default='', max_length=10, verbose_name='\u8fd4\u56de\u7801\u63cf\u8ff0\u4fe1\u606f')),
                ('type', models.CharField(default='', max_length=10, verbose_name='\u63a5\u53e3\u7c7b\u578b')),
                ('amt_item', models.CharField(default='', max_length=10, verbose_name='\u91d1\u989d\u660e\u7ec6')),
                ('bank_abbr', models.CharField(default='', max_length=10, verbose_name='\u652f\u4ed8\u94f6\u884c')),
                ('mobile', models.CharField(default='', max_length=10, verbose_name='\u652f\u4ed8\u624b\u673a\u53f7')),
                ('pay_date', models.CharField(default='', max_length=10, verbose_name='\u652f\u4ed8\u65f6\u95f4')),
                ('account_date', models.CharField(default='', max_length=10, verbose_name='\u4f1a\u8ba1\u65f6\u95f4')),
                ('status', models.CharField(default='', max_length=10, verbose_name='\u652f\u4ed8\u7ed3\u679c')),
                ('order_date', models.CharField(default='', max_length=10, verbose_name='\u8ba2\u5355\u63d0\u4ea4\u65e5\u671f')),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='\u8d39\u7528')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_recharge_list', to='authx.CustomerModel', verbose_name='\u5145\u503c\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u5145\u503c\u4fe1\u606f',
                'verbose_name_plural': '\u5145\u503c\u4fe1\u606f',
            },
        ),
    ]
