# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-16 06:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category1Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': '\u4e00\u7ea7\u5206\u7c7b',
                'verbose_name_plural': '\u4e00\u7ea7\u5206\u7c7b',
            },
        ),
        migrations.CreateModel(
            name='Category2Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category2_list', to='product.Category1Model')),
            ],
            options={
                'verbose_name': '\u4e8c\u7ea7\u5206\u7c7b',
                'verbose_name_plural': '\u4e8c\u7ea7\u5206\u7c7b',
            },
        ),
        migrations.CreateModel(
            name='Category3Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category3_list', to='product.Category2Model')),
            ],
            options={
                'verbose_name': '\u4e09\u7ea7\u5206\u7c7b',
                'verbose_name_plural': '\u4e09\u7ea7\u5206\u7c7b',
            },
        ),
        migrations.CreateModel(
            name='ChannelModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='\u4ea7\u54c1\u9891\u9053')),
                ('priority', models.IntegerField(default=0, verbose_name='\u4f18\u5148\u6743')),
                ('image', models.CharField(blank=True, max_length=256, null=True)),
                ('is_default', models.BooleanField(default=False, verbose_name='\u662f\u5426\u663e\u793a')),
            ],
            options={
                'verbose_name': '\u5546\u54c1\u9891\u9053',
                'verbose_name_plural': '\u5546\u54c1\u9891\u9053',
            },
        ),
        migrations.CreateModel(
            name='ProductImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=256, null=True, verbose_name='\u56fe\u7247')),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '\u5546\u54c1\u56fe\u7247',
                'verbose_name_plural': '\u5546\u54c1\u56fe\u7247',
            },
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=256, null=True, verbose_name='\u5546\u54c1\u7f16\u7801')),
                ('weight', models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='\u91cd\u91cf')),
                ('image', models.CharField(blank=True, max_length=256, null=True, verbose_name='\u4e3b\u56fe\u5730\u5740')),
                ('state', models.IntegerField(blank=True, choices=[(0, 'OffSale'), (1, 'OnSale')], default=0, verbose_name='\u4e0a\u4e0b\u67b6\u72b6\u6001')),
                ('brand', models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='\u54c1\u724c')),
                ('model', models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='\u578b\u53f7')),
                ('name', models.CharField(default='', max_length=256, null=True, verbose_name='\u5546\u54c1\u540d\u79f0')),
                ('manufacture_place', models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='\u5546\u54c1\u4ea7\u5730')),
                ('upc', models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='\u6761\u5f62\u7801')),
                ('sale_unit', models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='\u9500\u552e\u5355\u4f4d')),
                ('introduction', models.TextField(blank=True, default='', null=True, verbose_name='\u5546\u54c1\u63cf\u8ff0')),
                ('param', models.TextField(blank=True, default='', null=True, verbose_name='\u53c2\u6570\u7ec4')),
                ('credit_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11, null=True, verbose_name='\u4ea7\u54c1\u79ef\u5206')),
                ('last_sync', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='\u6700\u540e\u4e00\u6b21\u540c\u6b65\u65f6\u95f4')),
                ('source', models.IntegerField(choices=[(0, 'sn'), (1, 'jd'), (2, 'self')], default=0)),
                ('is_hot', models.BooleanField(default=False, verbose_name='\u662f\u5426\u70ed\u5356')),
                ('discount', models.IntegerField(blank=True, default=100, null=True, verbose_name='\u6298\u6263')),
                ('stock', models.IntegerField(blank=True, default=0, null=True, verbose_name='\u5e93\u5b58')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_list', to='product.Category3Model', verbose_name='\u4ea7\u54c1\u79cd\u7c7b')),
                ('category_d1', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_d1', to='product.Category1Model')),
                ('category_d2', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_d2', to='product.Category2Model')),
            ],
            options={
                'verbose_name': '\u5546\u54c1\u8be6\u60c5',
                'verbose_name_plural': '\u5546\u54c1\u8be6\u60c5',
            },
        ),
        migrations.AddField(
            model_name='productimagemodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_list', to='product.ProductModel', verbose_name='\u4ea7\u54c1\u540d'),
        ),
        migrations.AddField(
            model_name='channelmodel',
            name='product',
            field=models.ManyToManyField(related_name='channels_belong_to', to='product.ProductModel'),
        ),
    ]
