# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-23 08:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20170823_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_list', to='product.Category3Model', verbose_name='\u4e09\u7ea7\u5206\u7c7b'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='category_d1',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_d1', to='product.Category1Model', verbose_name='\u4e00\u7ea7\u5206\u7c7b'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='category_d2',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_d2', to='product.Category2Model', verbose_name='\u4e8c\u7ea7\u5206\u7c7b'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='credit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11, null=True, verbose_name='\u79ef\u5206\u4ef7\u683c'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='discount',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='\u6298\u6263'),
        ),
    ]
