# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-24 03:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20170823_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='is_show',
            field=models.BooleanField(default=True, verbose_name='\u662f\u5426\u663e\u793a'),
        ),
    ]
