# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-24 06:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_productmodel_is_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='last_change',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='\u6700\u540e\u4fee\u6539\u65f6\u95f4'),
        ),
    ]
