# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-24 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_productmodel_last_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11, null=True, verbose_name='\u6298\u6263'),
        ),
    ]
