# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-06 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_channelmodel_categtoy'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='is_big',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u662f\u5927\u56fe'),
        ),
    ]
