# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-21 08:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authx', '0003_customermodel_ipohe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customermodel',
            old_name='ipohe',
            new_name='phone',
        ),
    ]
