# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-21 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authx', '0004_auto_20170821_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermodel',
            name='phone',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
    ]
