# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-21 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authx', '0005_auto_20170821_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermodel',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Male'), (1, 'Female'), (2, 'Secrecy')], default=0, verbose_name='\u6027\u522b'),
        ),
    ]
