# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-22 02:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authx', '0006_auto_20170821_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='address',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='name',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='telephone',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
    ]
