# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-16 06:30
from __future__ import unicode_literals

from django.db import migrations, models
import utils.misc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageCircleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to=utils.misc.GetCategoryImageUpload, verbose_name='\u56fe\u7247')),
                ('redirect_type', models.IntegerField(choices=[(0, 'Keyword'), (1, 'Url')], default=0, verbose_name='\u7c7b\u578b')),
                ('content', models.CharField(default='', max_length=500, verbose_name='\u5185\u5bb9')),
                ('priority', models.IntegerField(default=0, verbose_name='\u4f18\u5148\u6743')),
                ('is_default', models.BooleanField(default=False, verbose_name='\u662f\u5426\u663e\u793a')),
            ],
            options={
                'verbose_name': '\u8f6e\u64ad\u56fe',
                'verbose_name_plural': '\u8f6e\u64ad\u56fe',
            },
        ),
        migrations.CreateModel(
            name='MiscModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='', max_length=500)),
                ('value', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
