# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-25 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecirclemodel',
            name='backend_image',
            field=models.IntegerField(default=0, verbose_name='\u80cc\u666f\u56fe\u7247'),
        ),
    ]
